language: java
jdk: oraclejdk11

script: mvn -e verify

after_success:
  - bash <(curl -s https://codecov.io/bush)

notifications:
  email:
    recipients:
    - nvsvkont@gmail.com
    on_failure: always
    on_success: never
